<?php 
$base_url =$block->get_base_url();
 ?>  
  <div class="filter-wrapper-done">
    <div class="breadcrumbs">
            <ul class="items">
                <li class="item home">
                    <a href="<?php echo $base_url; ?>" title="Go to Home Page">Home</a> 
                </li>

                <li class="item product">
                    <strong>Coffee Equipment</strong>
                </li>
            </ul>
          </div>
        <div class="container d-flex">
          <div class="page-title-wrapp">
            <h1 class="page-title">Coffee Equipment</h1>
          </div>
  
        </div>
     </div>