<?php
/**
 * @category Mageants StoreLocator
 * @package Mageants_StoreLocator
 * @copyright Copyright (c) 2017 Mageants
 * @author Mageants Team <support@Mageants.com>
 */
$apiKey=$block->getApiKey();
$store_id = $this->getRequest()->getParam("id");
$distance=0; $current=0; 
if($this->getRequest()->getParam("id")){
	$id=$this->getRequest()->getParam("id");
	if($id != ''){$collection=$block->getStoreById($id);}
	else{$collection=$block->getStoreCollection();}	
} else{
	$collection=$block->getStoreCollection(); 
}
?>
<script src='https://maps.googleapis.com/maps/api/js?key=<?php echo $apiKey; ?>&v=3.exp&libraries=places'></script>

<div id="store_list" class="list-store-box col-sm-4  pull-left">
	<div  class="page-title">
	
		<div class="list-store ">
			<div class="list-store-container disable-ul">
			<?php if(sizeOf($collection)==0){ echo "<strong style='margin-left:5px;'>No Store Found</strong>";}else { ?>
			<?php	$inc=0;	foreach($collection as $store): ?>
			<?php if($store['image'] != null) {	$imageUrl=$this->getUrl('pub/media/').$store['image'];}
				else { $imageUrl=$this->getViewFileUrl('Mageants_StoreLocator::images/map_with_pin.png');} ?>
				
				<div class="allstores-content">
				<div class="storepage-title">
					<h2 class="title">
					<span class="" aria-hidden="true"></span>
					<span>Store list</span>
					<span class="number-store pull-right"><?php echo sizeOf($collection); echo __(" Stores");?> </span>
					</h2>
				</div>
				<div class="mainstores show-tag-li store-item store-40 store-active <?php if($inc==0){ echo "left-active"; } $inc++; ?>"  data-store-id="<?php echo $store['id']; ?>" data-store-index="0" data-latitude="<?php echo $store['latitude']; ?>" data-longitude="<?php echo $store['longitude']; ?>" data-address="<?php echo $store['address']; ?>">
					<div class="mainstorlist">
						<div class="cols-3">
							<div class="tag-store">
								<img src="<?php echo $imageUrl; ?>">
								<p class="text-center"></p>
							</div>						
						</div>
						<div class="cols-9">
							<div class="tag-content">		
							<h4>
								<a id="store-link" class="title-store store-link" onclick="return false;"><?php echo __($store['sname']); ?>
									<input type="hidden" class="sl-latitude" value="<?php echo __($store['latitude']); ?>">
									<input type="hidden" class="sl-longitude" value="<?php echo __($store['longitude']); ?>">
								</a>
								</h4>
							<p class="address-store"><?php echo $store['address'].",".$store['region']." ".$store['city'].",".$store['country']; ?></p>
							<p class="phone-store"><?php echo $store['phone']; ?></p>
							<div class="tagstore-content">
							<a href="#" data-lat="<?php echo $store['latitude']; ?>" data-long="<?php echo $store['longitude']; ?>" class="btn-link streetview"><span ><?php echo __("Street View"); ?></span></a>
							<a herf="#" data-lat="<?php echo $store['latitude']; ?>" data-long="<?php echo $store['longitude']; ?>" data-div-no="<?php echo $inc; ?>" class="btn-link direction" ><span ><?php echo __("Direction"); ?></span></a>
							</div>
							</div>
							
						</div>
						
					</div>
					
					<div data-div-no="<?php echo $inc; ?>" class="option-direction custom-popup " style="padding: 0px;display: none;">
					    
					    <div id="directions-tool" class="directions-tool">
					    	<ul class="vertical text-center">
						        <li class="travel car active" data-traveling="DRIVING"><span>D</span></li>
						        <li class="travel bus" data-traveling="TRANSIT"><span>T</span></li>
						        <li class="travel walk" data-traveling="WALKING"><span>W</span></li>
						        <li class="travel bicycle" data-traveling="BICYCLING"><span>B</span></li>
						    </ul>
							<div class="form-inputs">
					            <input class="form-control origin originA start storelocator-originA-start" name="originA" isstart="true" autocomplete="off"  id="storelocator-originA-start" placeholder="Enter a location" type="text"> <br/>
					            <input class="form-control origin originB end" id="storelocator-originA-end" readonly="true" name="originB" autocomplete="off" value="<?php echo $store['address'].",".$store['city'].",".$store['country']; ?>" disabled type="text"> <br/>
					        </div>
					        <div class="directions-panel" id="directions-panel"></div>
					    </div>
					    <div class="box-input direction-go">
					        <button class="get-direction action primary pull-right" id="get_direction" title="Get Directions" type="submit">
					            <span><?php echo __("Go"); ?></span>
					        </button>
					    </div>
					</div>
				</div>
				</div>
				
				<div class="store-timings">
			        <div id="open_hour" class="open_hour">
						<div class="storepage-title opening">
			            <h2 class="title"><span><?php echo __("Opening hours"); ?></span></h2>
						</div>

			            <div class="table-responsive">
			                <table class="table table-time-schedule">
			                    <tbody>
			                        <tr id="sun_tr">
			                            <td class="time-label" style="text-align: center; width: 20%;"><?php echo __("Sun:"); ?> </td>
			                            <td></td>
			                            <?php if($store['sun_otime']!=''){ ?>
			                            <td><?php echo __("Open"); ?>
				                            <table style="display: none;" id="sun_time">
										        <tr>
										          <td><?php echo __("Opening Time :"); ?> <?php echo $store['sun_otime']; ?></td>
										          <td><?php echo __("Closing Time :"); ?> <?php echo $store['sun_ctime']; ?></td>
										        </tr>
										        <tr>
										          <td><?php echo __("Break Start Time :"); ?> <?php echo $store['sun_bstime']; ?></td>
										          <td><?php echo __("Break End Time :"); ?> <?php echo $store['sun_betime']; ?></td>
										        </tr>
									      </table>
			                            </td>
			                            <td id="sun_tr" class="open_schedule"><i class="arrow down"></i></td>
			                            <?php }else{?>
			                            <td><?php echo __("Closed"); ?> </td>
			                            <td></td>
			                            <?php } ?>
			                        </tr>
			                        <tr id="mon_tr">
			                            <td class="time-label" style="text-align: center; width: 20%;"><?php echo __("Mon:"); ?></td>
			                            <td></td><?php if($store['mon_otime']!=''){ ?>
			                            <td>Open
			                            	<table style="display: none;" class="mon_tr">
									        <tr>
									          <td><?php echo __("Opening Time :"); ?><?php echo str_replace(",", ":",$store['mon_otime']); ?></td>
									          <td><?php echo __("Closing Time :"); ?><?php echo str_replace(",", ":",$store['mon_ctime']); ?></td>
									        </tr>
									        <tr>
									          <td><?php echo __("Break Start Time :"); ?> <?php echo str_replace(",", ":",$store['mon_bstime']); ?></td>
									          <td><?php echo __("Break End Time :"); ?><?php echo str_replace(",", ":",$store['mon_betime']); ?></td>
									        </tr>
								      	</table>
			                            </td>
			                            <td id="mon_tr" class="open_schedule"><i class="arrow down"></i></td>
										<?php }else{?>
			                            <td><?php echo __("Closed"); ?> </td>
			                            <td></td>
			                            <?php } ?>
			                        </tr>
			                        <tr id="tue_tr">
			                            <td class="time-label" style="text-align: center; width: 20%;"><?php echo __("Tue:"); ?></td>
			                            <td></td><?php if($store['tue_otime']!=''){ ?>
			                            <td>Open <table style="display: none;" class="tue_tr">
									        <tr>
									          <td><?php echo __("Opening Time :"); ?><?php echo str_replace(",", ":",$store['tue_otime']); ?></td>
									          <td><?php echo __("Closing Time :"); ?><?php echo str_replace(",", ":",$store['tue_ctime']); ?></td>
									        </tr>
									        <tr>
									          <td><?php echo __("Break Start Time :"); ?>  <?php echo str_replace(",", ":",$store['tue_bstime']); ?></td>
									          <td><?php echo __("Break End Time :"); ?><?php echo str_replace(",", ":",$store['tue_betime']); ?></td>
									        </tr>
								      	</table>
								      </td>
								      <td id="tue_tr" class="open_schedule"><i class="arrow down"></i></td>
			                            <?php }else{?>
			                            <td><?php echo __("Closed"); ?> </td>
			                            <td></td>
			                            <?php } ?>
			                        </tr>
			                        <tr id="wed_tr">
			                            <td class="time-label" style="text-align: center; width: 20%;"><?php echo __("Wed:"); ?></td>
			                            <td></td><?php if($store['wed_otime']!=''){ ?>
			                            <td>Open
				                            <table style="display: none;" class="wed_tr">
										        <tr>
										          <td><?php echo __("Opening Time :"); ?><?php echo str_replace(",", ":",$store['wed_otime']); ?></td>
										          <td><?php echo __("Closing Time :"); ?><?php echo str_replace(",", ":",$store['wed_ctime']); ?></td>
										        </tr>
										        <tr>
										          <td><?php echo __("Break Start Time :"); ?>  <?php echo str_replace(",", ":",$store['wed_bstime']); ?></td>
										          <td><?php echo __("Break End Time :"); ?><?php echo str_replace(",", ":",$store['wed_betime']); ?></td>
										        </tr>
									      	</table>
									      </td>
									      <td id="wed_tr" class="open_schedule"><i class="arrow down"></i></td>
			                            <?php }else{?>
			                            <td><?php echo __("Closed"); ?> </td>
			                            <td></td>
			                            <?php } ?>
			                        </tr>
			                        <tr id="thu_tr">
			                            <td class="time-label" style="text-align: center; width: 20%;"><?php echo __("Thur:"); ?></td>
			                            <td></td><?php if($store['thu_otime']!=''){ ?>
			                            <td>Open
				                            <table style="display: none;" class="thu_tr">
											        <tr>
											          <td><?php echo __("Opening Time :"); ?><?php echo str_replace(",", ":",$store['thu_otime']); ?></td>
											          <td><?php echo __("Closing Time :"); ?><?php echo str_replace(",", ":",$store['thu_ctime']); ?></td>
											        </tr>
											        <tr>
											          <td><?php echo __("Break Start Time :"); ?><?php echo str_replace(",", ":",$store['thu_bstime']); ?></td>
											          <td><?php echo __("Break End Time :"); ?><?php echo str_replace(",", ":",$store['thu_betime']); ?></td>
											        </tr>
										      	</table>
									      </td>
									      <td id="thu_tr" class="open_schedule"><i class="arrow down"></i></td>
			                            <?php }else{?>
			                            <td><?php echo __("Closed"); ?> </td>
			                            <td></td>
			                            <?php } ?>
			                        </tr>
			                        <tr id="fri_tr">
			                            <td class="time-label" style="text-align: center; width: 20%;"><?php echo __("Fri:"); ?></td>
			                            <td></td><?php if($store['fri_otime']!=''){ ?>
			                            <td>Open
			                            	<table style="display: none;" class="fri_tr">
										        <tr>
										          <td><?php echo __("Opening Time :"); ?><?php echo str_replace(",", ":",$store['fri_otime']); ?></td>
										          <td><?php echo __("Closing Time :"); ?><?php echo str_replace(",", ":",$store['fri_ctime']); ?></td>
										        </tr>
										        <tr>
										          <td><?php echo __("Break Start Time :"); ?><?php echo str_replace(",", ":",$store['fri_bstime']); ?></td>
										          <td><?php echo __("Break End Time :"); ?><?php echo str_replace(",", ":",$store['fri_betime']); ?></td>
										        </tr>
									      	</table>
			                            </td>
			                            <td id="fri_tr" class="open_schedule"><i class="arrow down"></i></td>
			                            <?php }else{?>
			                            <td><?php echo __("Closed"); ?> </td>
			                            <td></td>
			                            <?php } ?>
			                        </tr>
			                        <tr id="sat_tr">
			                            <td class="time-label" style="text-align: center; width: 20%;"><?php echo __("Sat:"); ?></td>
			                            <td></td><?php if($store['sat_otime']!=''){ ?>
			                            <td>Open
			                            	<table style="display: none;" class="fri_tr">
										        <tr>
										          <td><?php echo __("Opening Time :"); ?><?php echo str_replace(",", ":",$store['sat_otime']); ?></td>
										          <td><?php echo __("Closing Time :"); ?><?php echo str_replace(",", ":",$store['sat_ctime']); ?></td>
										        </tr>
										        <tr>
										          <td><?php echo __("Break Start Time :");?><?php echo str_replace(",", ":",$store['sat_bstime']); ?></td>
										          <td><?php echo __("Break End Time :"); ?><?php echo str_replace(",", ":",$store['sat_betime']); ?></td>
										        </tr>
									      	</table>
			                            </td>
			                            <td id="sat_tr" class="open_schedule"><i class="arrow down"></i></td>
			                            <?php }else{?>
			                            <td><?php echo __("Closed"); ?> </td>
			                            <td></td>
			                            <?php } ?>
			                        </tr>
			                    </tbody>
			                </table>
			            </div>
			        </div>			        
				</div>
				<?php endforeach; } ?>
			</div>
		</div>
	</div>
</div>	
<script>
require(["jquery"], function($){
	$(document).ready(function($) {

		$(".table-time-schedule td.open_schedule").click(function(){
			var id=$(this).attr("id");
			jQuery("table."+id).slideToggle("slow");
			$(this).find(".arrow").toggleClass("down");
		});

		$(".btn-link.streetview").click(function(e){
			e.stopImmediatePropagation();
		var latitude=jQuery(this).attr("data-lat");
		var longitude=jQuery(this).attr("data-long");
		var baltimore = new google.maps.LatLng(latitude, longitude);
		var panoramaOptions = {
		    position: baltimore,
		    pov: {
		      heading: 34,
		      pitch: 10
		    }
		  };
		  var panorama = new google.maps.StreetViewPanorama(document.getElementById('pono'), panoramaOptions);
		  jQuery("#map").hide();
		  jQuery("#pono").show();
		});

		$(".btn-link.direction").click(function(e){
			e.stopImmediatePropagation();
			var divno=$(this).attr("data-div-no");
			$(".option-direction.active").removeClass("active");
			jQuery("div[data-div-no='"+divno+"']").addClass("active");

		});

		$("li.travel").click(function(e){
			e.preventDefault();
			jQuery(".travel.active").removeClass("active");
			jQuery(this).addClass("active");
		});
		
		$(".show-tag-li.store-item.store-40.store-active").click(function($){
			var latitude=parseFloat(jQuery(this).find(".sl-latitude").val());
			var longitude=parseFloat(jQuery(this).find(".sl-longitude").val());
			map.panTo(new google.maps.LatLng(latitude,longitude));
        	jQuery("#map").show();
			jQuery("#pono").hide();
		});

		$("#get_direction").click(function(e){
			e.preventDefault();
			var origin=jQuery("#storelocator-originA-start").val();
			var destination=jQuery("#storelocator-originA-end").val();
			if(origin=='')
			{
				jQuery("#storelocator-originA-start").css("box-shadow","0 0 3px 1px red");
			}
			else
			{
				var directionsService = new google.maps.DirectionsService();
				var directionsDisplay = new google.maps.DirectionsRenderer();
				var type=jQuery(".travel.active").attr("data-traveling");
				var map = new google.maps.Map(document.getElementById('map'), {
					zoom:5,
					mapTypeId: google.maps.MapTypeId.ROADMAP
				});
				
				directionsDisplay.setMap(map);
				directionsDisplay.setPanel(document.getElementById('directions-panel'));
				
				var request = {
					origin: origin, 
					destination: destination,
					travelMode: google.maps.TravelMode[type]
				};

				directionsService.route(request, function(response, status) {
					if (status == google.maps.DirectionsStatus.OK) {
						directionsDisplay.setDirections(response);
					}
				});
			}
		});
		jQuery('.storelocator-originA-start').each(function(){
			new google.maps.places.Autocomplete(
			  this, {
			    types: ['geocode']
			});
		});

	});
});
</script>
<style type="text/css">
	i {
    border: solid black;
    border-width: 0 3px 3px 0;
    display: inline-block;
    padding: 3px;
}
.arrow {
    transform: rotate(-135deg);
    -webkit-transform: rotate(-135deg);
}

.down {
    transform: rotate(45deg);
    -webkit-transform: rotate(45deg);
}
</style>