<?php
$session_email='';
$session_email = $block->getCustomerEmail();


// echo "<div style='background:red'>testing<br>";
// echo $session_email;
// echo "</div>";

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url_with_shop = $storeManager->getStore()->getBaseUrl();
$url = str_replace("shop/","",$url_with_shop);
if($session_email!='') {?>
    <script type="text/javascript">
          require([
              'jquery'
          ], function ($) 
          {
          jQuery(document).ready(function (e){
              
              jQuery.ajax({ 
                  url: "<?php echo $url;?>wp-json/wp/v2/autologinajax",
                  data: {"token":'Emqube_login',"email":"<?php echo $session_email; ?>"},
                  type: 'post',
                  success: function(result)
                  {
                      //console.log('testsuccess');
                      console.log(result);
                   
                  }
              });           
              
          });

          });

</script>

<?php

      
  }


  
?>
