<?php 
$base_url =$block->get_base_url();
 ?>  
<div class="breadcrumbs">
            <ul class="items">
                <li class="item home">
                    <a href="<?php echo $base_url; ?>" title="Go to Home Page">Home</a> 
                </li>

                <li class="item product">
                    <strong>Coffee Equipment</strong>
                </li>
            </ul>
          </div>