<?php
/**
 * Copyright © Postpay. All rights reserved.
 * See LICENSE for license details.
 */

/**
 * @var \Postpay\Payment\Block\Widget\Product $block
 */

use Magento\Framework\Json\Helper\Data;

?>

<div data-mage-init='{"postpayUi": <?= $this->helper(Data::class)->jsonEncode($block->getUiParams()) ?>}'>
    <div class="postpay-widget"
         data-type="product"
         data-amount="<?= $block->escapeHtmlAttr($block->getFinalPrice()->jsonSerialize()); ?>",
         data-currency="<?= $block->escapeHtmlAttr($block->getCurrencyCode()); ?>"
         data-locale="<?= $block->escapeHtmlAttr($block->getCurrentLocale()); ?>">
    </div>
</div>
