<?php
$baseurl = '';
$objectManager = '';
$customerSession = '';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create("Magento\Customer\Model\Session");

$baseurl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore(0)->getBaseUrl();
$wordpress_baseurl = str_replace("shop/", "", $baseurl);
?>

<li class="acc">
  <a href="javascript:void(0);">
    <svg class="icon icon-acc">
      <use xlink:href="<?php echo $wordpress_baseurl; ?>/wp-content/themes/karamcoffee/assets/img/icon-sprite.svg#icon-kc-acc"></use>
    </svg>
  </a>
  <ul class="acc-link">
    <?php

    if ($customerSession->isLoggedIn()) { ?>


      <li><a href="<?php echo $baseurl . 'customer/account/'; ?>">My Account</a></li>
      <!-- <li><a href="<?php //echo $wordpress_baseurl .'my-blogs'; 
                        ?>" target="_blank">My Blogs</a></li>  -->
      <li><a href="<?php echo $baseurl . 'customer/account/logout'; ?>">Sign Out</a></li>
    <?php
    } else { ?>
      <li><a href="<?php echo $baseurl . 'customer/account/'; ?>">My Account</a></li>
      <li><a href="<?php echo $baseurl . 'customer/account/login'; ?>">Sign In</a></li>

    <?php
    }
    ?>



  </ul>
</li>
<li class="toggle-menu">
  <a href="javascript:void(0);">
    <span></span>
    <span></span>
    <span>Explore</span>
  </a>
</li>