<?php
// $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
// $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
// $store = $storeManager->getStore();
// $baseUrl = $store->getBaseUrl();
// $baseSecureUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB, true);
$url = '';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url_with_shop = $storeManager->getStore()->getBaseUrl();
$url = str_replace("shop/", "", $url_with_shop);

$html = $this->getLayout()
  ->createBlock('Magento\Cms\Block\Block')
  ->setBlockId('custom_footer')
  ->toHtml();

if (preg_match('/<div[^>]*>(.*)<\/div>/is', $html, $matches)) {
  echo $matches[1];
}

?>


<div class="right">
  <img src="<?php echo $url; ?>/wp-content/themes/karamcoffee/assets/img/gain-an-exp-v1.svg" alt="gain-experience">
  <p>Earn a free tour of our Experience Lab to know the intricacies of beans and brewing. Like our Instagram page and fill up this form to get invited.</p>
  <div class="social-wrapp d-flex">
    <a href="<?php echo $url . "experience-lab" ?>" class="btn">Start here</a>
    <div class="social-menu">
      <p><span>Follow us on:</span>
        <a href="https://www.instagram.com/karamcoffee/" target="_blank" class="insta-social">
          <svg class="icon icon-insta">
            <use xlink:href="<?php echo $url; ?>/wp-content/themes/karamcoffee/assets/img/icon-sprite.svg#icon-kc-insta"></use>
          </svg>
        </a>
        <a href="https://www.facebook.com/Karam-Coffee-1448039912176904" target="_blank" class="insta-social">
          <svg class="icon icon-fb">
            <use xlink:href="<?php echo $url; ?>/wp-content/themes/karamcoffee/assets/img/icon-sprite.svg#icon-kc-fb"></use>
          </svg>
        </a>
        <a href="https://twitter.com/karamcoffee?s=09" target="_blank" class="insta-social">
          <svg class="icon icon-twitter">
            <use xlink:href="<?php echo $url; ?>/wp-content/themes/karamcoffee/assets/img/icon-sprite.svg#icon-kc-twitter"></use>
          </svg>
        </a>
      </p>
    </div>
  </div>
</div>