<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$baseUrl = $store->getBaseUrl();
$baseSecureUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB, true);
echo $this->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('custom_header')
->toHtml();


?>
<!-- <ul class="small-menu d-flex">
  <li><a href="<php //echo $baseSecureUrl ?>coffee/coffee">Coffee</a></li>
  <li><a href="<php //echo $baseSecureUrl ?>coffeeequipment/coffeeequipment">Equipment</a></li>
  <li><a href="javascript:void(0);">Offers</a></li>
</ul>
<ul class="small-menu d-flex">
  <li><a href="https://mohammeds44.sg-host.com/shop/coffee/coffee">Coffee</a></li>
  <li><a href="https://mohammeds44.sg-host.com/shop/coffeeequipment/coffeeequipment">Equipment</a></li>
  <li><a href="javascript:void(0);">Offers</a></li>
</ul> -->