 <!-- pride section starts -->
<?php 

 echo $this->getLayout()
          ->createBlock('Magento\Cms\Block\Block')
          ->setBlockId('pride_section')
          ->toHtml();

 ?>
    <!-- <section class="pride-wrapper">
      <div class="container">
        <h2 class="sec-title">Served with <span class="txt-med">Emirati Hospitality</span></h2>
        <ul class="list d-flex">
          <li>
            <div class="content">
              <img src="https://mohammeds44.sg-host.com/wp-content/themes/karamcoffee/assets/img/online.jpg" alt="">
              <h3>Online</h3>
              <p>Buy online from our webshop with flexible payment options and door delivery.</p>
            </div>
          </li>
          <li>
            <div class="content">
              <img src="https://mohammeds44.sg-host.com/wp-content/themes/karamcoffee/assets/img/karam-800.jpg" alt="">
              <h3>800 KARAM</h3>
              <p>Call our toll-free line to place your order and get answers to your queries.</p>
            </div>
          </li>
          <li>
            <div class="content">
              <img src="https://mohammeds44.sg-host.com/wp-content/themes/karamcoffee/assets/img/retail.jpg" alt="">
              <h3>Retail</h3>
              <p>Shop at prominent groceries that stock Karam Coffee power, beans and pods.</p>
            </div>
          </li>
          <li>
            <div class="content">
              <img src="https://mohammeds44.sg-host.com/wp-content/themes/karamcoffee/assets/img/hospitality.jpg" alt="">
              <h3>Hospitality</h3>
              <p>Enjoy Karam Coffee in premium hotel suites, airline lounges and cafes.</p>
            </div>
          </li>
          <li>
            <div class="content">
              <img src="https://mohammeds44.sg-host.com/wp-content/themes/karamcoffee/assets/img/Institution.jpg" alt="">
              <h3>Institution</h3>
              <p>Karam Coffee is served in government and private offices to guests and staff.</p>
            </div>
          </li>
        </ul>
      </div>
    </section> -->
    <!-- pride section ends -->