<?php
$helper = $this->helper(Magezon\AdvancedContact\Helper\Data::class);
$iconLoading = $helper->getIconLoading();
$keyCaptcha = $helper->getSecurityCaptchaKey();
?>
<script>
  var mgzContactPost = '<?= $block->escapeUrl($block->getFormAction()) ?>';
</script>
<form class="form contact mz-contact-form"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
        <div class="field note no-label">
            <?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?>
        </div>
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name" 
                       id="name" 
                       title="<?= $block->escapeHtmlAttr(__('Name')) ?>" 
                       value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('name') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserName()) ?>" 
                       class="input-text" 
                       type="text" 
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" 
                       id="email" 
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>" 
                       value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('email') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserEmail()) ?>" 
                       class="input-text" 
                       type="email" 
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="telephone" 
                       id="telephone" 
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" 
                       value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('telephone')) ?>" 
                       class="input-text" 
                       type="tel" />
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment">
                <span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span>
            </label>
            <div class="control">
                <textarea name="comment" 
                     id="comment"
                     title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                     class="input-text"
                     cols="5"
                     rows="3"
                     data-validate="{required:true}"><?= $block->escapeHtml($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
        <?php if ($block->getCaptchaStatus() == '1' && !empty($keyCaptcha)) { ?>
            <div class="g-recaptcha" data-sitekey="<?= $block->escapeHtml($keyCaptcha) ?>" data-callback="verifyCaptcha"></div>
            <div id="g-recaptcha-error"></div>
        <?php } ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" value="Submit" title="<?php echo __('Submit') ?>" class="action submit primary">
                <span><?php echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
<div class="mz_loadfr">
	<div class="mz_loadfr_bg">
	</div>
  <?php if (!empty($iconLoading)) {  ?>
    <img class="loading" src="<?= $iconLoading ?>" alt="">
  <?php } else { ?>
    <section class="loading">
        <div class="circle"></div>
        <div class="circle"></div>
        <div class="circle"></div>
    </section>
  <?php } ?>
</div>

<?php if ($block->getCaptchaStatus() == '1' && !empty($keyCaptcha)) { ?>
  <script src='https://www.google.com/recaptcha/api.js'></script>
<?php } ?>
<script type="text/javascript" src="<?php echo $block->getViewFileUrl('Magezon_AdvancedContact::js/custom_contact_form.js')?>"></script>